### ISSUE TITLE
PolybarConfig

### ISSUE THREAD

**Issue by ArchieFPL** [GideonWolfe/dots#1]
I loved your configs !!! Could you make the polybar files available? Thanks

**Comment by GideonWolfe** [comment]
My bad, totally forgot! Should be up now/

**Comment by H4ppy-04** [comment]
I'm not sure if all the files are there as I'm getting a strange error:
```
error: Uncaught exception, shutting down: Failed to open directory stream for /home/Josh/dotfiles/dotfiles/config/polybar/modules (reason: No such file or directory)
```
